### ISSUE TITLE
How to tell vscode about bqn?

### ISSUE THREAD

**Issue by borgauf** [razetime/bqn-vscode#13]
This is my settings.json

    "security.workspace.trust.untrustedFiles": "open",
    "window.zoomLevel": 2
}

{
    "editor.formatOnSave": true,
    "haskell.hlint.logLevel": "warn",
    "haskell.hlint.run": "onSave",
    "haskell.formattingProvider": "ormolu",
    "bqn.executablePath": "/usr/local/bin/bqn",
  
    // May be necessary
   // "haskell.hlint.executablePath": "<path-to-hlint>"
  }

on my Ubuntu 22.10. But it errors out with Ctr-Shift-Enter with The terminal process failed to launch: Path to shell executable "cbqn" does not exist. Should I just do a symbolic link? Total Beginner to vscode, BTW.

**Comment by razetime** [comment]
i'm sorry, this feature is a little broken now. However, some fixes from #12 will be merged soon, and i will notify you on this thread when it's pushed to marketplace.

**Comment by razetime** [comment]
It should be available now, is the problem fixed?

**Comment by borgauf** [comment]
I've created a symbolic link between bqn and cbqn on my Ubuntu system and now it appears to work with Ctr-Shif-Return. But now I can't figure out how to get a glyph tablet up. How can I display the symbol table in VS Code? Sorry I'm a total beginner.

**Comment by razetime** [comment]
There was an idea adding the symbol table to the sidebar. As of now if you press `\` and then do `Ctrl+Space`, you should get completion prompts for all the primitives.

**Comment by razetime** [comment]
I've added a symbol table as a todo. Some new instructions are in the README as well. thanks
