### ISSUE TITLE
Minor discoloring with ‿

### ISSUE THREAD

**Issue by Brian-ED** [razetime/bqn-vscode#15]
![image](https://user-images.githubusercontent.com/72316548/210157557-90ddc7db-44bf-4d31-9216-289917e4bd0d.png)
First line has first Hello being blue, second is white, and _hello is also white. 
Second and third line show that for underscore names it's broken in a similar way.

theoretically you should write arrays of vars with lowercase and no underscores anyways, but sometimes i want to signify that an array of values will be used as functions, or just a specific value.

**Comment by razetime** [comment]
seems like `‿` is not recognized as a word boundary. It's a weird unicode thing, probably, I'll add a special case for stranding.

Please paste the exact text you used when you have an issue with highlighting.

**Comment by razetime** [comment]
from my tests this should be correct. The changes are on the marketplace, please do tell me if it works correctly on v0.1.2.
