### ISSUE TITLE
Latin1 characters aren't added yet

### ISSUE THREAD

**Issue by Brian-ED** [razetime/bqn-vscode#16]
Latin1 characters (àáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞ) don't seem to be highlighted correctly
Example:
![image](https://user-images.githubusercontent.com/72316548/211904056-0ed73d67-c4c4-4fcb-9590-4db151cbda33.png)
(note, that π isn't broken. It only appears green because the character before it is broken)

**Comment by Brian-ED** [comment]
uh i just realized top line. i included it by accident.

**Comment by razetime** [comment]
again, please paste the actual text you ahve from your screenshots. I will get to this soon.

**Comment by Brian-ED** [comment]
```
Døπ←1⊸+
•Show Døπ 10
```
oh sorry. will remember for next time.

**Comment by razetime** [comment]
this should be fixed on the latest commit. Can you clone the repository and tell me whether it works correctly for your latin1 names?

**Comment by Brian-ED** [comment]
I have cloned the latest commit but I don't know how to activate the highlighting

**Comment by razetime** [comment]
Ctrl-Shift-P ->  run and debug.

**Comment by razetime** [comment]
fixed in 440e68083e6ef9fca2965c9aab7a29bd2bf1d1e9.
