### ISSUE TITLE
Link on gliph description isn't working

### ISSUE THREAD

**Issue by Brian-ED** [razetime/bqn-vscode#17]
I'm on windows, and when i click the "Pervasive" link it asks me to create a file "arthmetic.md" at location "C:\doc\". 
![image](https://user-images.githubusercontent.com/72316548/212136333-fe13d859-324a-43a5-a096-61ca2f2ccfe1.png)

**Comment by mk12** [comment]
Hm, my conservation script must have missed that kind of link. I’ll take a look.
