### ISSUE TITLE
Add completion by function name

### ISSUE THREAD

**Issue by VOID404** [razetime/bqn-vscode#18]
Would it be possible to add a completion based on function name, akin to [BQNPAD](https://bqnpad.mechanize.systems/) completion? It really lowers the barrier of entry, when you can type `shape` and get a correct symbol, when you don't remember them all by heart yet.

**Comment by razetime** [comment]
added in [406620d](https://github.com/razetime/bqn-vscode/commit/406620d010a986e3ed7ab338d167206cdfbc0bf3).
