### ISSUE TITLE
Dubble struck character description not showing

### ISSUE THREAD

**Issue by Brian-ED** [razetime/bqn-vscode#19]
when i hover over a double struck character, the descriptions aren't showing. I haven't tested all symbols, but after testing all double struck characters 𝕩𝕏𝕗𝔽𝕘𝔾𝕣 and a few other non struck symbols, it seems only the double strucked are broken.

**Comment by razetime** [comment]
i assume it is because they don't have repl help pages, and hence the autogeneration doesn't have data to show for them on hover.

**Comment by Brian-ED** [comment]
It looks like they are implemented here:
https://github.com/razetime/bqn-vscode/blob/4e388a48dd1b256ae4f53c1cd448b1ccb244009e/src/help.json#L4

**Comment by mk12** [comment]
You are right, they're in help.json so it ought to show up on hover. I'll take a look.
