### ISSUE TITLE
Syntax highlighting not working properly.

### ISSUE THREAD

**Issue by jacobusmmsmit** [razetime/bqn-vscode#20]
Hello,

Coming from BQNpad I expected a similar experience in VSCode, colour-wise. However, I can't seem to get BQN's syntax highlighting to work. Here's how it look:
![image](https://user-images.githubusercontent.com/57063134/213771995-2219b86c-08e0-4e75-a6f8-347a41c7a9a9.png)

Is anyone else having this issue?

**Comment by razetime** [comment]
oh, sorry for the delay. Can you tell me which theme this is?

**Comment by jacobusmmsmit** [comment]
No worries, I'm using Gruvbox Dark (Medium) from [Gruvbox Themes](https://marketplace.visualstudio.com/items?itemName=tomphilbin.gruvbox-themes).

**Comment by razetime** [comment]
oh, one more thing, please paste the text. always happens in the syntax highlighting issues.

**Comment by razetime** [comment]
I have added new scopes, which you can check  by installing from the repository. From what I can see, the colors are now distinct.
If that is ok, his will be in v0.1.3 once issue 16 is complete.

**Comment by jacobusmmsmit** [comment]
Apologies for not pasting the text, silly of me. Thank you for addressing this :)
