### ISSUE TITLE
Scaler characters show as blue

### ISSUE THREAD

**Issue by Brian-ED** [razetime/bqn-vscode#22]
Scalar characters like 'a' and 'b' show as blue. it'd make more sense for them to be orange like "a" and "b".

**Comment by razetime** [comment]
This is purely based on theme. A universal color scheme for every theme is not possible in vscode, and there is no exact mapping for bqn either.

**Comment by Brian-ED** [comment]
That's confusing because it has worked about a week ago.

**Comment by razetime** [comment]
it might have been an error, since many color classes were incorrectly specified and highlighting regexes had many holes in them. If this does become a bigger problem I will consider changing the classes.

**Comment by Brian-ED** [comment]
alright

**Comment by Brian-ED** [comment]
I feel like i should clarify my question. You said the color is dependent on theme, but what my issue is, is that strings and scalar characters don't have the same color. Scalar characters have the same color as functions/Uppercase names.

**Comment by razetime** [comment]
post a picture and copy paste the text, please.

**Comment by Brian-ED** [comment]
![image](https://user-images.githubusercontent.com/72316548/217019999-a3e97b91-8fc0-424d-8e57-a900a2ea0916.png)
```
Abc
'abc'
'a'
"abc"
"a"
```

**Comment by razetime** [comment]
yeah, it's a theme-centric problem. 
![image](https://user-images.githubusercontent.com/11015319/217020393-d324b084-8e2d-4fb0-8944-2b17e8eec545.png)
![image](https://user-images.githubusercontent.com/11015319/217020503-6de492ad-3cc0-43b1-9d7b-74155b77b6f8.png)

(also, there are two different color scopes for strings and scalar characters in every theme. It is expected that they are in different colors.)

**Comment by Brian-ED** [comment]
why not have scalars be the same color as strings?

**Comment by razetime** [comment]
let's take this discussion to chat, it will be faster that way.

**Comment by Brian-ED** [comment]
I assume you mean the BQN chat in APL farm
