### ISSUE TITLE
Input by primitive name

### ISSUE THREAD

**Issue by jariji** [razetime/bqn-vscode#26]
I'm a beginner and I can't remember how to type the primitives, and looking them up all the time is too time-consuming. I wonder if there is a solution to this. 

In some other languages, I can type `\circ` to get the `∘` symbol. I realize there's a conflict between having `\c` immediately converting to `↓` versus it being the start of `\circ`, but I wonder if there's some way to get functionality that's similar in spirit. Perhaps a separate mode for primitive-name entry where it doesn't convert until I press `tab`, or a separate prefix key for verbose entry.

**Comment by mk12** [comment]
I believe if you press backlash and then the shortcut to invoke autocompletion (Ctrl+Space on Windows), it will give the functionality you’re looking for. I’m on my phone now but I can confirm later today.

**Comment by jariji** [comment]
Turns out I can just type the name directly, no `\`.
