### ISSUE TITLE
Backslash substitution does not work properly when Vim extension is enabled

### ISSUE THREAD

**Issue by zopsicle** [razetime/bqn-vscode#28]
When used together with the [Vim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) extension, if the cursor is before a character, completing a backslash substitution places the cursor after that character, instead of after the newly inserted character. For instance, in the below screen capture, the cursor is expected to be positioned before the `f` instead of after the `f` after the substitution:

https://github.com/razetime/bqn-vscode/assets/50083900/20b90105-27ac-41ab-b06a-a308b313bfef

Another issue is that, when entering a command (press `:` in normal mode), backslashes cannot be inserted into the command; they are instead inserted into the file:

https://github.com/razetime/bqn-vscode/assets/50083900/1b548f82-6a12-4cf2-b34b-95c7480462bb

Using BQN language v0.1.5 and Vim v1.26.0.

**Comment by razetime** [comment]
I doubt i can address interactions with other extensions properly. However, if you have a system-wide input method that works in vscode, I can add an option to disable backslash substitution.

**Comment by razetime** [comment]
Backslash can be disabled in the upcoming version 0.1.6.
