### ISSUE TITLE
System Function descriptions don't show

### ISSUE THREAD

**Issue by sohang3112** [razetime/bqn-vscode#30]
Hovering over system functions like `•Out` doesn't show their description - it would be nice to have these as well.

**Comment by sohang3112** [comment]
@razetime Is there any update regarding this yet?

**Comment by coolbluewater** [comment]
Sadly, it looks like @razetime [passed away](https://www.arraycast.com/episodes/episode83-jelly) recently.

**Comment by sohang3112** [comment]
> Sadly, it looks like @razetime [passed away](https://www.arraycast.com/episodes/episode83-jelly) recently.

I'm very sorry to hear that. @coolbluewater do you know who is maintaining this repo now?

**Comment by coolbluewater** [comment]
@sohang3112 probably nobody.

**Comment by mk12** [comment]
That is very sad news, I was wondering what that podcast title meant but hadn’t listened to it…


I have contributed to this repo a fair amount so I can try to maintain it, and look into this issue soon.

**Comment by mk12** [comment]
Starting to look into this. It will require scraping [spec/system.md](https://raw.githubusercontent.com/mlochbaum/BQN/master/spec/system.md) which should be easy. The regex `` '^\|\s*`(•\w+)`\s*\|\s*(.*)$' `` matches each system function name $1 and description $2. I will update gen_help_writer.lua to do that.

I think probably the way it should work is hovering directly on the bullet should still give the general bullet/system docs, but hovering anywhere in the word to the right of it should give the specific system function description.

**Comment by mk12** [comment]
I have implemented this in master. However, I don't have permission to publish the extension on the VS Code marketplace. I guess I'll probably have to publish my own copy of it. If I do that, I wonder if I should also use my fork of the repo and do further development there.

**Comment by sohang3112** [comment]
> I don't have permission to publish the extension on the VS Code marketplace. I guess I'll probably have to publish my own copy of it.

@mk12 [This VS Code issue](https://github.com/Microsoft/vscode/issues/21478) for transferring ownership of extensions recommends deprecating the old extension so that VS Code will prompt users to install the new extension.

**Comment by mk12** [comment]
Unfortunately I can't deprecate the extension for the same reason that I can't re-publish it myself. But I've published a new extension and added a note to the description which should hopefully point people in the right direction:

<img width="356" alt="Screenshot 2024-10-03 at 6 44 08 PM" src="https://github.com/user-attachments/assets/d8e55875-e22d-422c-aeef-b3e7054d506e">

This new BQN extension is 0.1.7 and includes the system function docs (the subject of this issue).

See #32 for more details.

**Comment by sohang3112** [comment]
Thanks @mk12
