### ISSUE TITLE
Character insertion when using vim plugin

### ISSUE THREAD

**Issue by KilianVounckx** [razetime/bqn-vscode#31]
I am using the [vim](https://github.com/VSCodeVim/Vim) plugin. I don't know if this is an issue with them or with this plugin, or just the interactions between the two.
When I want to insert a bqn primitive to the left of some other text, the cursor jumps one character too far to the right.

E.g. If I have a file with contents:
```
Hello, World!
```
If the cursor is between the o and r in world, and I want to type a special character like ↕, the cursor ends up between r and l, instead of still being before r.

Curiously, this only happens when entering some characters. The 'double letters' like 𝕩 and 𝕎 don't have the same problem.

**Comment by razetime** [comment]
please tell me if the advice in the readme related to `bqn.enableBackslashCompletion` helps ([link](https://github.com/razetime/bqn-vscode#configurable-settings)).

**Comment by KilianVounckx** [comment]
I did not see that, my bad. I just tried it however and it did not change anything. When I enter the `bqn.enableBackslashCompletion` in my settings file, it says it is an `Unknown Configuration Setting`.

**Comment by razetime** [comment]
oh, yes, it's part of the current dev release. I'll publish a minor patch to the package registries soon.

**Comment by KilianVounckx** [comment]
I see, I'll try it again in a while then. Thank you!

**Comment by KilianVounckx** [comment]
I tried it in the release branch and it worked.
