### ISSUE TITLE
[request] Upload on Open VSX registry

### ISSUE THREAD

**Issue by Mrfiregem** [razetime/bqn-vscode#6]
[Open-VSX](https://open-vsx.org/) is an alternate extension marketplace that's used by default for vscodium users and people running Arch Linux. It'd be nice if you made this extension available there as well.

**Comment by razetime** [comment]
Thanks for telling! It'll be done by today. I also need to publish my recent changes to the telemetry side's marketplace, so I think i'll get both of them in.

**Comment by razetime** [comment]
@Mrfiregem It is now on the registry on this link: https://open-vsx.org/extension/razetime/bqn-language
