### ISSUE TITLE
How to add strand using backslash?

### ISSUE THREAD

**Issue by andrewnc** [razetime/bqn-vscode#8]
Forgive my ignorance, but I am trying to add ‿ using the vscode extension, but aside from ctrl-space and searching, I can't seem to get it to work. 

Would love some pointers here, and thank you for such a great extension!!

**Comment by razetime** [comment]
bqn-vscode uses the [standard BQN keymap](https://mlochbaum.github.io/BQN/keymap.html), which is also used in the [online REPL](https://mlochbaum.github.io/BQN/try.html). For `‿`, the expansion is `\+space`. I tested it just now on vscode 1.65.2 on ubuntu. Kindly do tell me if it works correctly.

**Comment by razetime** [comment]
I have mentioned the keymap in the README file now.
